version: '3.8'

services:
  web:
    build: .
    expose:
      - 8000:5000
    volumes:
      - ./qr_codes:/app/qr_codes
      - ./data:/app/data
    restart: unless-stopped
    container_name: minor-project
    networks:
      - app-network


networks:
  app-network:
    driver: bridge